name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout tests repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install test dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npm run install:browsers

    - name: Clone RWA app
      run: |
        git clone https://github.com/cypress-io/cypress-realworld-app .rwa
        cd .rwa
        corepack enable || true
        yarn install --frozen-lockfile

    - name: Start RWA app (frontend + backend)
      run: |
        cd .rwa
        yarn dev &> /tmp/rwa.log &
        npx wait-on http-get://localhost:3000 http-get://localhost:3001 --timeout 120000

    - name: Check RWA services (debug)
      run: |
        echo "Front (3000):"
        curl -sI http://localhost:3000 || true
        echo "API (3001):"
        curl -sI http://localhost:3001 || true
        tail -n 50 /tmp/rwa.log || true

    - name: Set environment variables
      run: |
        echo "BASE_URL=http://localhost:3000" >> $GITHUB_ENV
        echo "API_URL=http://localhost:3001" >> $GITHUB_ENV
        echo "PW_TIMEOUT=60000" >> $GITHUB_ENV
        echo "PW_EXPECT_TIMEOUT=20000" >> $GITHUB_ENV

    - name: Run Smoke tests
      run: npm run test:smoke -- --reporter=html --output=playwright-report/smoke
      env:
        BASE_URL: http://localhost:3000
        API_URL: http://localhost:3001

    - name: Run API tests
      run: npm run test:api -- --reporter=html --output=playwright-report/api
      env:
        BASE_URL: http://localhost:3000
        API_URL: http://localhost:3001

    - name: Run UI tests
      run: npm run test:ui -- --reporter=html --output=playwright-report/ui
      env:
        BASE_URL: http://localhost:3000
        API_URL: http://localhost:3001

    - name: Combine reports for upload
      if: always()
      run: |
        echo "Combining reports:"
        ls -R playwright-report || true
        mkdir -p combined-report
        cp -r playwright-report/smoke combined-report/ 2>/dev/null || true
        cp -r playwright-report/api combined-report/ 2>/dev/null || true
        cp -r playwright-report/ui combined-report/ 2>/dev/null || true
        echo "Combined structure:"
        ls -R combined-report || true

    - name: Upload combined report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-combined-report
        path: combined-report/**
        retention-days: 30
        if-no-files-found: warn


  publish-report:
    name: Publish HTML Reports (Pages)
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download combined report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-combined-report
          path: site

      - name: Prepare site content
        run: |
          echo "Site dir:"
          ls -R site || true
          mkdir -p site/_site
          mv site/* site/_site/ || true
          echo "Final structure:"
          ls -R site/_site || true

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show Pages URL
        run: |
          echo "✅ Reports published at:"
          echo "https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
