name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout tests repo
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install test dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Clone RWA app
      run: |
        git clone https://github.com/cypress-io/cypress-realworld-app .rwa
        cd .rwa
        corepack enable || true
        yarn install --frozen-lockfile
        
    - name: Start RWA app
      run: |
        cd .rwa
        yarn dev &
        npx wait-on http-get://localhost:3000 --timeout 60000
        
    - name: Set environment variables
      run: |
        echo "BASE_URL=http://localhost:3000" >> $GITHUB_ENV
        echo "API_URL=http://localhost:3001" >> $GITHUB_ENV
        echo "PW_TIMEOUT=30000" >> $GITHUB_ENV
        echo "PW_EXPECT_TIMEOUT=8000" >> $GITHUB_ENV
        
    - name: Run Smoke tests
      run: npm run test:smoke
      
    - name: Run API tests
      run: npm run test:api
      
    - name: Run UI tests
      run: npm run test:ui
      
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30
        
    - name: Upload traces and videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: |
          test-results/
          playwright-report/
        retention-days: 30

  smoke-only:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout tests repo
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install test dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps
      
    - name: Clone RWA app
      run: |
        git clone https://github.com/cypress-io/cypress-realworld-app .rwa
        cd .rwa
        corepack enable || true
        yarn install --frozen-lockfile
        
    - name: Start RWA app
      run: |
        cd .rwa
        yarn dev &
        npx wait-on http-get://localhost:3000 --timeout 60000
        
    - name: Run Smoke tests only
      run: npm run test:smoke
      env:
        BASE_URL: http://localhost:3000
        API_URL: http://localhost:3001